---
- name: Check status nginx
  hosts: 192.168.1.218
  become: yes
  tasks:
    - name: Check status of nginx
      ansible.builtin.service_facts:

    - name: Display nginx service status
      debug:  
        var: services['nginx.service']

    - name: check Nginx version
      ansible.builtin.shell: nginx -v
      register: nginx_version
      ignore_errors: yes

    - name: Display Nginx version
      debug:
        var: nginx_version.stderr_lines

    - name: stopped nginx service
      ansible.builtin.service:
        name: nginx
        state: stopped
      when: services['nginx.service'].state == 'running'

    - name: Display nginx service status after stopping
      debug:  
        var: services['nginx.service']














    # - name: Stop nginx service
    #   ansible.builtin.service:
    #     name: nginx
    #     state: stopped
    #     when: services['nginx.service'].state == 'running'