---
- name: Delete nginx
  hosts: 192.168.1.218
  become: yes
  tasks:
    - name: Check status of nginx service
      ansible.builtin.systemd:
        name: nginx
        state: status
      register: nginx_service_status
      ignore_errors: yes

    - name: Display nginx service status
      debug:
        var: nginx_service_status

    # - name: Stop nginx service if running
    #   ansible.builtin.systemd:
    #     name: nginx
    #     state: stopped
    #   when: nginx_service_status.status == 0

    # - name: Display message about nginx service stopped
    #   debug:
    #     msg: "Nginx service has been stopped."
    #   when: nginx_service_status.status == 0