---
- name: Check status nginx
  hosts: 192.168.1.218
  become: yes

  tasks:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Set nginx service fact (safe lookup)
      ansible.builtin.set_fact:
        nginx_svc: >-
          {{ ansible_facts.services['nginx.service']
             | default(ansible_facts.services['nginx'] | default(None)) }}

    - name: Show nginx service status
      ansible.builtin.debug:
        msg: "nginx state={{ nginx_svc.state | default('not installed') }}, enabled={{ nginx_svc.enabled | default('unknown') }}"

    - name: Check Nginx version
      ansible.builtin.command: nginx -v
      register: nginx_version
      failed_when: false
      changed_when: false

    - name: Display Nginx version output
      ansible.builtin.debug:
        msg: "{{ nginx_version.stderr | default(nginx_version.stdout) | default('nginx not installed') }}"

    - name: Stop nginx if running
      ansible.builtin.service:
        name: nginx
        state: stopped
      when:
        - nginx_svc is mapping
        - nginx_svc.state is defined
        - nginx_svc.state == 'running'
    
    - name: Re-gather service facts after possible stop
      ansible.builtin.service_facts:

    - name: Display nginx service status after actions
      ansible.builtin.debug:
        msg: "{{ ansible_facts.services['nginx.service'] | default(ansible_facts.services['nginx'] | default('not installed')) }}"
