---
- name: Delete nginx
  hosts: 192.168.1.218
  become: yes
  tasks:
    - name: Gather installed packages
      ansible.builtin.package_facts: 
    
    - name: debug installed nginx version
      debug:
        var: ansible_facts.packages

    # - name: Check status of nginx service
    #   ansible.builtin.systemd:
    #     name: nginx
    #     state: started
    #   register: nginx_service_status
    #   ignore_errors: yes