---
- name: Start service nginx
  hosts: 192.168.1.218
  become: yes

  tasks:
    - name: check status nginx
      ansible.builtin.service_facts:
    
    - name: Set nginx service fact (safe lookup)
      debug:
        msg: >-
          {{ ansible_facts.services['nginx.service']
             | default(ansible_facts.services['nginx'] | default('not installed')) }}