---
- name: Start service nginx
  hosts: 192.168.1.218
  become: yes

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:
    
    - name: Set nginx service fact (safe lookup)
      ansible.builtin.set_fact:
        nginx_svc: >-
          {{ ansible_facts.services['nginx.service']
             | default(ansible_facts.services['nginx'] | default(None)) }}

    - name: Display nginx service status before actions
      ansible.builtin.debug:
        msg: "nginx state={{ nginx_svc.state | default('not installed') }}, enabled={{ nginx_svc.enabled | default('unknown') }}"

    # - name: Start nginx if not running
    #   ansible.builtin.service:
    #     name: nginx
    #     state: started
    #   when:
    #     - nginx_svc is not none
    #     - nginx_svc.state != 'running'

    # - name: Re-gather service facts after start
    #   ansible.builtin.service_facts: